// Generates assets/css/tokens.css. Run: node scripts/tokens.mjs > assets/css/tokens.css
// Colour roles come from Google's material-color-utilities on the 2025 (Expressive) spec,
// seeded with the Droidspaces app's dark primary. Motion easings are the M3 Expressive spring
// specs (Compose ExpressiveMotionTokens.kt) solved into CSS linear() point lists.
// Needs: npm i @material/material-color-utilities@0.4.0
import { argbFromHex, hexFromArgb, Hct, SchemeTonalSpot, MaterialDynamicColors } from "@material/material-color-utilities";

const SOURCE = "#7DC4E4"; // Android/app/.../ui/theme/Color.kt, ThemePalette.CATPPUCCIN.primaryDark
const ROLES = ["primary","onPrimary","primaryContainer","onPrimaryContainer","secondary","onSecondary","secondaryContainer","onSecondaryContainer","tertiary","onTertiary","tertiaryContainer","onTertiaryContainer","error","onError","errorContainer","onErrorContainer","surface","surfaceDim","surfaceBright","surfaceContainerLowest","surfaceContainerLow","surfaceContainer","surfaceContainerHigh","surfaceContainerHighest","onSurface","onSurfaceVariant","outline","outlineVariant","inverseSurface","inverseOnSurface","inversePrimary","primaryFixed","primaryFixedDim","onPrimaryFixed","onPrimaryFixedVariant"];
const kebab = s => s.replace(/([A-Z])/g, m => "-" + m.toLowerCase());
const scheme = dark => new SchemeTonalSpot(Hct.fromInt(argbFromHex(SOURCE)), dark, 0, "2025", "phone");
const role = (r, dark) => hexFromArgb(MaterialDynamicColors[r].getArgb(scheme(dark)));

// Spring solver: x(0)=1, v(0)=0, returns CSS linear() over the settle time.
function spring(zeta, k, n = 24) {
  const w0 = Math.sqrt(k);
  const x = t => zeta < 1
    ? Math.exp(-zeta * w0 * t) * (Math.cos(w0 * Math.sqrt(1 - zeta * zeta) * t) + (zeta / Math.sqrt(1 - zeta * zeta)) * Math.sin(w0 * Math.sqrt(1 - zeta * zeta) * t))
    : Math.exp(-w0 * t) * (1 + w0 * t);
  let last = 0; for (let t = 0; t < 5; t += 0.001) if (Math.abs(x(t)) >= 0.0005) last = t;
  const T = last + 0.02;
  const pts = Array.from({ length: n + 1 }, (_, i) => (1 - x(T * i / n)).toFixed(4).replace(/\.?0+$/, ""));
  pts[n] = "1";
  return { ms: Math.round(T * 1000), css: `linear(${pts.join(", ")})` };
}
const SPRINGS = { "spatial-fast": [0.6, 800], "spatial-default": [0.8, 380], "spatial-slow": [0.8, 200], "effects-fast": [1, 3800], "effects-default": [1, 1600] };

let out = `/* Generated by scripts/tokens.mjs. Do not edit. Source colour ${SOURCE}, M3 2025 spec. */\n:root {\n  color-scheme: light dark;\n`;
for (const r of ROLES) out += `  --md-sys-color-${kebab(r)}: light-dark(${role(r, false)}, ${role(r, true)});\n`;
out += `\n  --md-sys-shape-corner-xs: 4px; --md-sys-shape-corner-sm: 8px; --md-sys-shape-corner-md: 12px;\n  --md-sys-shape-corner-lg: 16px; --md-sys-shape-corner-lg-increased: 20px; --md-sys-shape-corner-xl: 28px;\n  --md-sys-shape-corner-xl-increased: 32px; --md-sys-shape-corner-xxl: 48px; --md-sys-shape-corner-full: 9999px;\n\n`;
for (const [name, [z, k]] of Object.entries(SPRINGS)) { const s = spring(z, k); out += `  --motion-${name}: ${s.ms}ms ${s.css};\n`; }
out += `  --motion-press: 350ms cubic-bezier(0.42, 1.67, 0.21, 0.9); /* @material/web 2.5.0 expressive button */\n}\n:root[data-theme="light"] { color-scheme: light; }\n:root[data-theme="dark"] { color-scheme: dark; }\n`;
process.stdout.write(out);
